/*---------------------------------------------------------- 
MASV: 46.01.104.075
NHOM: MOVE ON THINGS
LAB: 04 Nhom
NGAY:
----------------------------------------------------------*/ 
-- cau a﻿
CREATE DATABASE QLSV_lab4
Go

USE QLSV_lab4

Go
-- cau b
CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20),
	LUONG VARBINARY (MAX),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
	CONSTRAINT PK_MANV PRIMARY KEY (MANV),
)
GO
CREATE TABLE LOP
(
	MALOP VARCHAR(20),
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20),
	CONSTRAINT PK_MALOP PRIMARY KEY (MALOP),
	CONSTRAINT FK_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV),
)
GO
CREATE TABLE SINHVIEN
(
	MASV NVARCHAR(20),
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME,
	DIACHI NVARCHAR(200),
	MALOP VARCHAR(20),
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY(MAX) NOT NULL,
	CONSTRAINT PK_MASV PRIMARY KEY (MASV),
	CONSTRAINT FK_MALOP FOREIGN KEY (MALOP) REFERENCES LOP (MALOP)
)
-- Câu c
--i) Stored dùng để thêm mới dữ liệu (Insert) vào table SINHVIEN 
create procedure SP_INS_ENCRYPT_SINHVIEN 
(
	@MASV nvarchar(20),
	@HOTEN nvarchar(100),
	@NGAYSINH datetime,
	@DIACHI nvarchar(200),
	@MALOP varchar(20),
	@TENDN nvarchar(100),
	@MATKHAU varchar(max)
)
as
begin 
	insert into SINHVIEN(MASV,HOTEN,NGAYSINH,DIACHI,MALOP,TENDN,MATKHAU) 
	values(@MASV,@HOTEN,@NGAYSINH,@DIACHI,@MALOP,@TENDN,CONVERT(varbinary(max),@MATKHAU))
end
--mật khẩu: 12345

select * from SINHVIEN

--ii) Stored dùng để thêm mới dữ liệu (Insert) vào table NHANVIEN, trong đó thuộc tính MATKHAU được mã hóa (HASH) sử dụng SHA1 
--và thuộc tính LUONG sẽ được mã hóa sử dụng thuật toán AES 256, với khóa mã hóa là mã số của sinh viên thực hiện bài Lab này

CREATE MASTER KEY ENCRYPTION BY PASSWORD = '4501104000'
CREATE CERTIFICATE MyCertificate_DPN ENCRYPTION BY PASSWORD = '4501104000' WITH SUBJECT = 'INS_NV'
CREATE SYMMETRIC KEY SSN_Key_INS_NV WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE MyCertificate_DPN
GO 
CREATE PROCEDURE SP_INS_ENCRYPT_NHANVIEN
@MANV NVARCHAR(20), @HOTEN NVARCHAR(100),@EMAIL VARCHAR(20), @LUONG varchar(max), @TENDN NVARCHAR(100),@MATKHAU VARCHAR(max)
AS
BEGIN
	OPEN SYMMETRIC KEY SSN_Key_INS_NV
	DECRYPTION BY CERTIFICATE MyCertificate_DPN WITH PASSWORD ='4501104000'

	INSERT INTO NHANVIEN VALUES(@MASV,@HOTEN,@EMAIL,CONVERT(VARBINARY(MAX),@LUONG),@TENDN,CONVERT(VARBINARY(MAX),@MATKHAU))
	CLOSE SYMMETRIC KEY SSN_Key_INS_NV
END



SELECT * FROM dbo.NHANVIEN
GO

create PROC SP_PASS @PASS VARCHAR(MAX)
AS
BEGIN 
	SELECT CONVERT(VARBINARY(MAX), HASHBYTES('SHA1', @PASS)) AS MD5
END
GO
EXEC SP_PASS '123456'
SELECT * FROM dbo.NHANVIEN

--iii)Stored dùng để truy vấn dữ liệu nhân viên (NHANVIEN) 
CREATE PROCEDURE SP_SEL_ENCRYPT_NHANVIEN
AS
BEGIN
	OPEN SYMMETRIC KEY SSN_Key_INS_NV
	DECRYPTION BY CERTIFICATE MyCertificate_DPN WITH PASSWORD ='4501104000'
	SELECT MANV,HOTEN,EMAIL,CONVERT(VARCHAR(max),LUONG) as LUONGCB
	FROM NHANVIEN
	CLOSE SYMMETRIC KEY SSN_Key_INS_NV
END

EXEC SP_SEL_ENCRYPT_NHANVIEN
GO 

-- d) dang nhap
create PROCEDURE LoginNV(
        @UserName NVARCHAR(100),
        @Password VARCHAR(max)
)
AS
BEGIN	
	SELECT COUNT(*)FROM NHANVIEN WHERE TENDN = @UserName and MATKHAU = @Password
END
GO 
SELECT * FROM dbo.NHANVIEN


